/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradingProgramsIndexRouteImport } from './routes/trading-programs.index'
import { Route as TradingProgramsSizeRouteImport } from './routes/trading-programs.$size'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingProgramsIndexRoute = TradingProgramsIndexRouteImport.update({
  id: '/trading-programs/',
  path: '/trading-programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingProgramsSizeRoute = TradingProgramsSizeRouteImport.update({
  id: '/trading-programs/$size',
  path: '/trading-programs/$size',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partner': typeof PartnerRoute
  '/rules': typeof RulesRoute
  '/trading-programs/$size': typeof TradingProgramsSizeRoute
  '/trading-programs/': typeof TradingProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partner': typeof PartnerRoute
  '/rules': typeof RulesRoute
  '/trading-programs/$size': typeof TradingProgramsSizeRoute
  '/trading-programs': typeof TradingProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partner': typeof PartnerRoute
  '/rules': typeof RulesRoute
  '/trading-programs/$size': typeof TradingProgramsSizeRoute
  '/trading-programs/': typeof TradingProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/how-it-works'
    | '/partner'
    | '/rules'
    | '/trading-programs/$size'
    | '/trading-programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/how-it-works'
    | '/partner'
    | '/rules'
    | '/trading-programs/$size'
    | '/trading-programs'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/how-it-works'
    | '/partner'
    | '/rules'
    | '/trading-programs/$size'
    | '/trading-programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PartnerRoute: typeof PartnerRoute
  RulesRoute: typeof RulesRoute
  TradingProgramsSizeRoute: typeof TradingProgramsSizeRoute
  TradingProgramsIndexRoute: typeof TradingProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading-programs/': {
      id: '/trading-programs/'
      path: '/trading-programs'
      fullPath: '/trading-programs/'
      preLoaderRoute: typeof TradingProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading-programs/$size': {
      id: '/trading-programs/$size'
      path: '/trading-programs/$size'
      fullPath: '/trading-programs/$size'
      preLoaderRoute: typeof TradingProgramsSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  HowItWorksRoute: HowItWorksRoute,
  PartnerRoute: PartnerRoute,
  RulesRoute: RulesRoute,
  TradingProgramsSizeRoute: TradingProgramsSizeRoute,
  TradingProgramsIndexRoute: TradingProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
